spring.application.name=api-rest-pdf2img

# Tamaño maximo de un solo archivo
spring.servlet.multipart.max-file-size=20MB

# Tamaño maximo de la petici�n completa (pueden ser varios archivos)
spring.servlet.multipart.max-request-size=20MB

# Serializaci�n de JSON en Hibernate para compatibilidad de Spring Boot 4 y Jackson 3
spring.jpa.properties.hibernate.type.json_format_mapper=dev.code925.pdf2img.utils.CustomHibernateJsonFormatter